# Generated by Django 5.1.4 on 2025-03-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_designation_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
