# Generated by Django 5.1.4 on 2025-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bloodGroup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
